-- 0004_reports.sql — periodic LLM nutrition reports
--
-- Weekly and monthly reports are generated by the `scheduled` handler and
-- stored here. One row per period; `sent_reminders.reminder_key` is what
-- guarantees a period is only ever generated once (see src/reports.ts).

CREATE TABLE reports (
  id             TEXT PRIMARY KEY,
  period_kind    TEXT NOT NULL,           -- 'weekly' | 'monthly'
  period_key     TEXT NOT NULL,           -- '2026-W34' | '2026-08'
  period_start   TEXT NOT NULL,           -- local date, inclusive (YYYY-MM-DD)
  period_end     TEXT NOT NULL,           -- local date, inclusive (YYYY-MM-DD)
  model          TEXT NOT NULL,
  payload_json   TEXT NOT NULL,           -- exactly what was sent to the model
  report_json    TEXT NOT NULL,           -- parsed model output
  days_logged    INTEGER NOT NULL,
  days_in_period INTEGER NOT NULL,
  created_at     TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (period_kind, period_key)
);

CREATE INDEX reports_kind_start ON reports (period_kind, period_start DESC);

-- The vision path stays on gemini-flash; report analysis is a separate model.
ALTER TABLE settings ADD COLUMN report_model TEXT NOT NULL DEFAULT 'moonshotai/kimi-k3';
