/**
 * One-command local setup for a new engineer.
 *
 *   node scripts/bootstrap-dev.mjs
 *
 * Writes .dev.vars with a freshly generated local passphrase so the app runs
 * immediately without anyone handing over production credentials. Nothing here
 * touches the live Worker, the live database, or the real secrets.
 */
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";

const target = path.resolve(".dev.vars");
if (fs.existsSync(target)) {
  console.log(".dev.vars already exists — leaving it alone.");
  process.exit(0);
}

// Readable but unguessable, so a shared dev machine is not wide open.
const words = ["mate", "milanesa", "quinoa", "lentil", "papaya", "fennel", "cocoa", "saffron", "walnut", "basil", "ginger", "melon"];
const pick = () => words[crypto.randomInt(words.length)];
const devPassphrase = `${pick()}-${pick()}-${pick()}-${crypto.randomInt(1000, 9999)}`;

fs.writeFileSync(target, `# Generated by scripts/bootstrap-dev.mjs. Local only, never deployed.
# These are NOT the production secrets and must never be.

APP_PASSWORD=${devPassphrase}

# Body photos. Any value works locally; omit it and the app passphrase is used.
PHOTO_PASSPHRASE=1234

# Optional. Without it, photo and text analysis fall back to the local food
# matcher and everything else still works. Get your own key at
# https://openrouter.ai/settings/keys — do not reuse production's.
OPENROUTER_API_KEY=

# Optional, only needed to exercise the Telegram webhook locally.
TELEGRAM_WEBHOOK_SECRET=
`);

console.log(`Wrote .dev.vars

  app passphrase   ${devPassphrase}
  photo passphrase 1234

Next:
  pnpm d1:migrate:local
  pnpm dev            then sign in at http://localhost:5173 with the passphrase above
`);
