/**
 * Exports the local SQLite diary into SQL that D1 can import, and copies the
 * meal photos out of data/uploads so they can be pushed into KV.
 *
 *   npx tsx scripts/export-local-to-d1.ts
 *
 * Produces:
 *   tmp/d1-import.sql          — run with `wrangler d1 execute macroflow --remote --file`
 *   tmp/kv-photos/upload.sh    — the `wrangler kv key put` calls for each photo
 *
 * Foods are skipped: they come from migrations/0002_seed_foods.sql. Benchmark
 * tables are skipped too; the research lab stays local.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { DatabaseSync } from "node:sqlite";

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const db = new DatabaseSync(path.join(rootDir, "data", "macroflow.db"));
const outputDir = path.join(rootDir, "tmp");
fs.mkdirSync(outputDir, { recursive: true });

const literal = (value: unknown): string => {
  if (value === null || value === undefined) return "NULL";
  if (typeof value === "number") return String(value);
  return `'${String(value).replace(/'/g, "''")}'`;
};

function insertsFor(table: string, columns: string[]) {
  const rows = db.prepare(`SELECT ${columns.join(", ")} FROM ${table}`).all() as Array<Record<string, unknown>>;
  if (!rows.length) return { sql: `-- ${table}: no rows\n`, count: 0 };
  const values = rows.map((row) => `  (${columns.map((column) => literal(row[column])).join(", ")})`).join(",\n");
  return { sql: `INSERT OR REPLACE INTO ${table} (${columns.join(", ")}) VALUES\n${values};\n`, count: rows.length };
}

const settingsColumns = [
  "id", "name", "onboarding_complete", "calorie_target", "protein_target", "carbs_target", "fat_target",
  "weight_kg", "height_cm", "age", "sex", "activity", "goal", "theme", "plate_diameter_cm",
  "openrouter_model", "telegram_bot_token", "telegram_chat_id", "timezone", "reminders_json"
];

const parts = [
  "-- Generated by scripts/export-local-to-d1.ts. Foods come from the seed migration.\n",
  insertsFor("settings", settingsColumns),
  insertsFor("meals", ["id", "logged_at", "meal_type", "title", "image_path", "image_paths_json", "notes", "source", "confidence"]),
  insertsFor("meal_items", ["id", "meal_id", "food_id", "name", "grams", "calories", "protein", "carbs", "fat"]),
  insertsFor("weight_entries", ["id", "recorded_at", "weight_kg"]),
  insertsFor("meal_memories", ["id", "subject", "note", "times_used", "created_at", "updated_at"])
];

const sql = parts.map((part) => (typeof part === "string" ? part : part.sql)).join("\n");
const sqlPath = path.join(outputDir, "d1-import.sql");
fs.writeFileSync(sqlPath, sql);

const counts = parts.filter((part): part is { sql: string; count: number } => typeof part !== "string");
console.log(`Wrote ${path.relative(rootDir, sqlPath)}`);
console.log(counts.map((part, index) => `  ${["settings", "meals", "meal_items", "weight_entries", "meal_memories"][index]}: ${part.count}`).join("\n"));

// meal_items references food_id from the local foods table. The seed migration
// recreates the same 41 foods in the same insertion order, so the ids line up;
// flag it loudly if the local database has drifted from the seed.
const foodCount = Number((db.prepare("SELECT COUNT(*) count FROM foods").get() as { count: number }).count);
if (foodCount !== 41) {
  console.warn(`\n!! Local foods table has ${foodCount} rows, the seed migration has 41.`);
  console.warn("   Check that meal_items.food_id still points at the right foods after import.");
}

const uploadsDir = path.join(rootDir, "data", "uploads");
const photos = fs.existsSync(uploadsDir) ? fs.readdirSync(uploadsDir).filter((file) => /\.(jpe?g|png)$/i.test(file)) : [];
const kvDir = path.join(outputDir, "kv-photos");
fs.mkdirSync(kvDir, { recursive: true });
const script = [
  "#!/usr/bin/env bash",
  "# Generated by scripts/export-local-to-d1.ts",
  "# Pushes local meal photos into the PHOTOS KV namespace.",
  "set -euo pipefail",
  "",
  ...photos.map((file) => {
    const contentType = /\.png$/i.test(file) ? "image/png" : "image/jpeg";
    const source = path.posix.join("data", "uploads", file);
    return `wrangler kv key put "uploads/${file}" --path "${source}" --binding PHOTOS --remote --metadata '{"contentType":"${contentType}"}'`;
  })
].join("\n");
fs.writeFileSync(path.join(kvDir, "upload.sh"), `${script}\n`);
console.log(`\nWrote ${photos.length} photo upload command(s) to ${path.relative(rootDir, path.join(kvDir, "upload.sh"))}`);
