/**
 * Regenerates migrations/0002_seed_foods.sql from shared/seed.ts so the food
 * table in D1 always matches the local seed data.
 *
 *   npx tsx scripts/generate-seed-migration.ts
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { seedFoods } from "../shared/seed.js";

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const quote = (value: string) => `'${value.replace(/'/g, "''")}'`;

const rows = seedFoods.map((food) => [
  quote(food.name),
  quote(food.brand ?? ""),
  quote(food.category),
  quote(food.emoji),
  quote(food.servingLabel),
  String(food.servingGrams),
  String(food.calories),
  String(food.protein),
  String(food.carbs),
  String(food.fiber),
  String(food.fat),
  quote(JSON.stringify(food.aliases))
].join(", "));

const sql = `-- Generated by scripts/generate-seed-migration.ts from shared/seed.ts.
-- Do not edit by hand; re-run the script instead.

INSERT OR IGNORE INTO foods (name, brand, category, emoji, serving_label, serving_grams, calories, protein, carbs, fiber, fat, aliases) VALUES
${rows.map((row) => `  (${row})`).join(",\n")};
`;

const target = path.join(rootDir, "migrations", "0002_seed_foods.sql");
fs.writeFileSync(target, sql);
console.log(`Wrote ${seedFoods.length} foods to ${path.relative(rootDir, target)}`);
